version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: dev-spotlight-postgres
    environment:
      POSTGRES_DB: dev-spotlight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  dev-spotlight:
    image: dev-spotlight-backend:latest  # Replace with your Docker image name
    container_name: dev-spotlight-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dev-spotlight
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET: 0f493ef996e5bc380eead86d6f1fc2ca46e7426d
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID: 37a93236e0e10d7dffd0
      FRONTEND_URL: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - postgres
